name = "saddle-library-airtable-proxy"
main = "src/index.js"
compatibility_date = "2026-06-02"

[vars]
AIRTABLE_TABLE_NAME = "Saddles"
AIRTABLE_VIEW = "Grid view"
AIRTABLE_BORROWERS_TABLE = "Borrowers"
AIRTABLE_CHECKOUTS_TABLE = "Checkout Requests"
EMAIL_FROM = "Saddle Library <saddlelibary@psl.kellbot.com>"
ADMIN_EMAIL = "saddlelibary@kellbot.com"
